# Generated by Django 5.2.9 on 2025-12-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la obra')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('technique', models.CharField(help_text='Ej: Óleo sobre lienzo, Bronce fundido', max_length=200, verbose_name='Técnica/Materiales')),
                ('dimensions', models.CharField(blank=True, help_text='Ej: 120x80 cm', max_length=100, verbose_name='Dimensiones')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Año de realización')),
                ('description', models.TextField(blank=True, verbose_name='Historia / Descripción')),
                ('cover_image', models.ImageField(upload_to='artworks/covers/', verbose_name='Imagen de Portada')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible en la web')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, help_text='Ej: Vista lateral, Detalle de textura', max_length=200, verbose_name='Pie de foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.artwork', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la categoría')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Portada')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='portfolio.category', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='portfolio.category', verbose_name='Categoría'),
        ),
    ]
