# Generated by Django 5.2.9 on 2025-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Artístico')),
                ('bio', models.TextField(verbose_name='Biografía / Sobre mí')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Foto de perfil')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
            ],
            options={
                'verbose_name': 'Perfil del Artista',
                'verbose_name_plural': 'Perfil del Artista',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre (ej: Instagram)')),
                ('url', models.URLField(verbose_name='Enlace URL')),
                ('icon_class', models.CharField(blank=True, help_text='Clase de icono (ej: bi bi-instagram o fa-brands fa-instagram)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['order'],
            },
        ),
    ]
